include:
  - project: 'xfce/xfce4-dev-tools'
    file: '/ci/build_project.yml'

build-no-x11:
  extends: .make
  before_script:
    - ./autogen.sh --disable-x11
  stage: build
  script:
    - make

build-no-wayland:
  extends: .make
  before_script:
    - ./autogen.sh --disable-wayland
  stage: build
  script:
    - make

meson-no-x11:
  before_script:
    - apt install -y meson ninja
  stage: build
  script:
    - mkdir -p build
    - meson -Dx11=disabled ..
    - ninja

meson-no-x11:
  before_script:
    - apt update
    - apt install -y meson
  stage: build
  script:
    - mkdir -p build
    - meson -Dwayland=disabled ..
    - ninja
